#!/bin/sh
run() {
    state=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | tr -s ' ' | cut -d ' ' -f3)
    bat=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | tr -s ' ' | cut -d ' ' -f3 | sed 's/.$//')
    echo $state $bat
    if [[ "$state" == 'discharging' ]] && [[ "$bat" -le 20 ]]; then
        # echo "low battery";
        notify-send -a "Power" -u critical "Low battery"
    fi
}
