#!/bin/sh

echo "received $1"
if [[ "$1" == "restore" ]]; then
  xrandr --output HDMI-A-0 --off --output eDP --mode 1920x1080
  export PRIMARY=eDP 
elif [[ "$1" == "extend" ]]; then
  xrandr --output HDMI-A-0 --mode 1920x1080 --output eDP --mode 1920x1080 --right-of HDMI-A-0
  export PRIMARY=HDMI-A-0 SECONDARY=eDP
elif [[ "$1" == "mirror" ]]; then
  xrandr --output HDMI-A-0 --mode 1920x1080 --same-as eDP --output eDP --mode 1920x1080 --primary
  export PRIMARY=eDP
elif [[ "$1" == "default" ]]; then
  xrandr --output HDMI-A-0 --mode 1920x1080 --same-as eDP --output eDP --off
  export PRIMARY=HDMI-A-0
else
  echo "Usage: fl_display (restore|extend|mirror|default)"
  exit
fi
