#!/bin/sh

filename="${1%.*}"
if zip --show-files $1 | grep -q "creating: $filename/"; then
  echo "File is wrapped properly."
  unzip "$1"
else
  echo "Creating $filename directory"
  mkdir "$filename"
  mv "$1" "$filename"
  cd "$filename"
  if [[ "$?" -ne "0" ]]; then
    echo "ERROR!"
    return
  fi
  unzip "$1"
  mv "$1" ..
  cd ..
fi
