#!/bin/sh

#: This is for prefixing/suffixing files with _
#: (.*\/)?([^\/]+)(\/.*)?$

if [ -z "$2" ]; then
  echo "usage: -(u|s) <filename>"
  return
fi

cur=`echo $2 | sed -E 's/(.*\/)?([^\/]+)(\/.*)?$/\2/g'`
echo "renaming... $cur"

if [[ $1 == "-u" ]]; then
  echo "mark as unsolved"
  new="_$cur"
elif [[ $1 == "-s" ]]; then
  echo "mark as solved"
  new="${cur}_"
else
  echo "unknown flag"
  return
fi

mv "$cur" "$new"
