#! /bin/sh
# vim:fileencoding=utf-8:foldmethod=marker

#: dual monitor set up {{{

#: if an external monitor is connected, use that only
if type "xrandr"; then
    monitors=$(xrandr --query | grep " connected" | cut -d" " -f1)
    if [[ ${a[*]} =~ "HDMI-1" ]]; then
        PRIMARY="HDMI-1"
        SECONDARY="eDP-1"
        source ~/.bashrc
        external_monitor
    else
        PRIMARY="eDP-1"
    fi
else
    PRIMARY="eDP-1"
fi

#: }}}

#: bswpm configuration {{{
bspc monitor -d I II III IV V VI VII VIII IX

#: Multiple monitors config. More help see
#: https://github.com/baskerville/bspwm/issues/522
#: https://github.com/baskerville/bspwm/issues/148
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#: Configure look and feel of bspwm
bspc config border_width         2
bspc config normal_border_color  
bspc config focused_border_color \#FF9900
bspc config split_ratio          0.5
bspc config window_gap           12
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#: Configure rules for windows
#: Example: bspc rule -a Gimp desktop='^8' state=floating follow=on

#: }}}

#: desktop environment apps {{{

#: hotkey daemon, bar, and window compositor for lightweight "DE"-experience
sxhkd &
$HOME/.config/polybar/launch.sh
picom --config ~/.config/picom/picom.conf &

#: wallpaper and desktop widgets
#: set the correct locale for conky to display CJK characters properly! 
feh --bg-fill ~/Pictures/Wallpapers/anime/wp4088544.jpg
LC_CTYPE=zh_CN.utf8 LC_TIME=en_US.utf8 conky -c ~/.config/conky/conky.conf

#: }}}

#: autostart useful apps {{{

redshift -l 1.290270:103.851959 &
safeeyes -e &

#: }}}

#: input configurations {{{

#: touchpad
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Natural Scrolling Enabled' 1

#: chinese input
ibus-daemon -drx

#: apl keyboard
setxkbmap -layout us,apl -variant ,dyalog -option grp:caps_switch

#: }}}

