#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V VI VII VIII IX
#bspc monitor HDMI-1 -d X

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
# Multiple monitors config. More help see
# https://github.com/baskerville/bspwm/issues/522
# https://github.com/baskerville/bspwm/issues/148

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color \#FF9900

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#***REMOVED***
***REMOVED***
#***REMOVED***
compton --config ~/.config/compton/compton.conf &
conky -c ~/.config/conky/conky.conf
~/Documents/BSPWM/startupConfig.sh
