#! /bin/sh

# dual monitor set up
if type "xrandr"; then
    monitors=$(xrandr --query | grep " connected" | cut -d" " -f1)
    if [[ ${a[*]} =~ "HDMI-1" ]]; then
        PRIMARY="HDMI-1"
        SECONDARY="eDP-1"
        source ~/.bashrc
        external_monitor
    else
        PRIMARY="eDP-1"
    fi
else
    PRIMARY="eDP-1"
fi
export $PRIMARY
export $SECONDARY

sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
# Multiple monitors config. More help see
# https://github.com/baskerville/bspwm/issues/522
# https://github.com/baskerville/bspwm/issues/148

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color \#FF9900

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

feh --bg-fill ~/Pictures/Wallpapers/anime/wp4088544.jpg
compton --config ~/.config/compton/compton.conf &
LC_CTYPE=zh_CN.utf8 LC_TIME=en_US.utf8 conky -c ~/.config/conky/conky.conf

# touchpad
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Natural Scrolling Enabled' 1

# chinese input
ibus-daemon -drx

# redshift
redshift -l 1.290270:103.851959 &
